# Site settings
baseurl = "https://burag.com/"
themesDir = "themes"
languageCode = "en-us"
title = "Burag Cetinkaya"
theme = "hugo-cactus-theme"
# Enter your tracking code to enable Google Analytics
googleAnalytics = ""
# Disable comments by leaving disqusShortname empty
disqusShortname = "solutionsthinking"

[params]
  name = "Burag Cetinkaya"
  description = "Engineering Management | Software | Entrepreneurship"
  bio = "Technology Leader. Programmer. Soccer fan."
  # Enter optionally your twitter account
  twitter = "buragc"
  enableRSS = false

  # Add custom assets with their paths relative to the static folder
  customCSS = []
  customJS  = []

  # The variables below are optionally too and can be used to
  # translate or customize each string of the theme.

  # Navigation links
  home = "home"
  about = "about me"
  blog = "posts"
  work = "work"
  subscribe = "Subscribe"
  # Pagination links
  olderPosts = ""
  newerPosts = ""
  readMore = ""
  copyright = "Copyright 2017 Burag Cetinkaya"
  # Sharing options and author information in posts
  aboutAuthor = "I am the core & data engineering director at Meetup. Love managing engineering teams and writing code."
  tweet = "Tweet"
  share = "Share"
  # 404 page
  title404 = ""
  subtitle404 = ""

  # Choose a font for the social icons in the footer. Either "mono-social" or "font-awesome"
  iconFont = "mono-social"
    # The social icons can be styled differently if you use mono as font - circle, rounded, or empty
    socialIconStyle = "rounded"

# Add additional social link entries underneath
[social]
    twitter  = "https://www.twitter.com/buragc"
    email    =  "mailto:burag@burag.com"
    github   = "https://www.github.com/buragc"
    linkedin = "https://www.linkedin.com/in/buragc"